services:
  whatsapp_go:
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    image: "aldinokemal2104/go-whatsapp-web-multidevice:latest"
    build:
      context: .
      dockerfile: ./docker/golang.Dockerfile
    #restart: 'always'
    volumes:
      - ./statics:/app/statics
      - ./storages:/app/storages
    ports:
      - "3500:3000"
    environment:
      API_WEBHOOK: https://webhook.site/2480f7d6-9eed-40c3-bf49-415c4990ee5c
      ENV_MYAPPLICATION: "Nebula Zap 4.21.1"
