version: '3.9'
services:
  whatsapp_go:
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    image: "aldinokemal2104/go-whatsapp-web-multidevice:latest"
    build:
      context: .
      dockerfile: ./docker/golang.Dockerfile
    #restart: 'always'
    volumes:
      - ./statics:/app/statics
      - ./storages:/app/storages
    ports:
      - "3500:3000"
    environment:
      API_WEBHOOK: https://webhook-test.com/3c9f4be60f658d598affa9a3915b3d17
      webhook: https://webhook-test.com/3c9f4be60f658d598affa9a3915b3d17
      ENV_MYAPPLICATION: "Nebula Zap 2.1"
