services:
  whatsapp_go:
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    image: "aldinokemal2104/go-whatsapp-web-multidevice:latest"
    build:
      context: .
      dockerfile: ./docker/golang.Dockerfile
    #restart: 'always'
    volumes:
      - ./statics:/app/statics
      - ./storages:/app/storages
    ports:
      - "3500:3000"
    environment:
      API_WEBHOOK: https://9102-2804-14d-c282-8a33-c19e-898e-ac18-5739.ngrok-free.app/api/Webhook/receive/storeId/1601759d-c5e9-4ec8-a3e9-e8b7da49caf5
      ENV_MYAPPLICATION: "Nebula Zap 2.1"
